version: '3.8'

services:
  web:
    image: flask-app
    build: .
    ports:
      - "8080:5000"
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
