apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
data:
  prometheus.yml: |
    global:
      scrape_interval: 1s
    rule_files:
      - /etc/prometheus/alert.rules
    scrape_configs:
      - job_name: 'flask-app'
        static_configs:
          - targets: ['flask-app-service:5000']
  alert.rules: |
    groups:
    - name: crash-alert
      rules:
        - alert: Error
          expr: job:http_errors_per_second:rate5m{job="flask-app"} > 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "The application has crashed"
            description: "The application has crashed"

