apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    rule_files:
      - /etc/prometheus/rules/*.rules.yml

    scrape_configs:
      - job_name: 'flask-app'
        static_configs:
          - targets: ['flask-app-service:5000']

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:9093']
      
      route:
        group_by: ['alertname']
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 3h
        receiver: 'slack-notifications'
      
      receivers:
        - name: 'slack-notifications'
          slack_configs:
            - send_resolved: true
              channel: '#general'
              api_url: 'https://hooks.slack.com/services/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sz4Qk'
