apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-app-rc
spec:
  replicas: 3  # Set the desired number of replicas
  selector:
    app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: serriaguirregaray/flask-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongodb-service
